### ISSUE TITLE
Does it support multithreading? Is it lock free?

### ISSUE THREAD

**Issue by loongs-zhang** [orxfun/orx-priority-queue#22]

**Comment by orxfun** [comment]
Hi @loongs-zhang . I believe you already found the answer before my response. Still do not want to leave it unanswered:

* The priority queue traits are designed for single threaded usage.
* Likewise, the d-ary heap implementations are not meant to be `Send` across multiple threads.

I did work on implementing lock free concurrent collections but have never worked on a concurrent priority queue represented as a heap. Sounds challenging but also very interesting. Hope I can focus on this at some point.

**Comment by loongs-zhang** [comment]
I'm currently using `crossbeam_skiplist::SkipMap<c_longlong, Vec<T>>`, but it is not exactly what I want because the priority may be the same. The second type of `SkipMap` uses `Vec`, which still cannot fully utilize CPU cache. Speaking of which, I think you can refer to `crossbeam_skiplist`.
